# Generated by Django 5.0.1 on 2024-04-19 18:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
                ('address', models.TextField(blank=True, max_length=255, null=True)),
                ('province', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(default='Thailand', max_length=255)),
                ('is_foster_family', models.BooleanField(default=False)),
                ('is_shelter', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shelter', to='adopt.organization')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat')], default='DOG', max_length=255)),
                ('breed', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('FEMALE', 'Female'), ('MALE', 'Male')], max_length=6, null=True)),
                ('age', models.CharField(choices=[('PUPPY', 'Puppy'), ('YOUNG', 'Young'), ('ADULT', 'Adult'), ('SENIOR', 'Senior')], max_length=20, null=True)),
                ('size', models.CharField(blank=True, choices=[('S', 'Small (1-10kg)'), ('M', 'Medium (11-26kg)'), ('L', 'Large (27-45kg)'), ('EX', 'Extra Large (46+kg)')], max_length=20, null=True)),
                ('description', models.TextField(max_length=2000, null=True)),
                ('registered_date', models.DateField(auto_now_add=True, null=True)),
                ('energy', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('anxiety', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('sterilized', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('vaccinated', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='uploads/adopt/')),
                ('dog_friendly', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('cat_friendly', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('kid_friendly', models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('house_trained', models.CharField(blank=True, choices=[('YES', 'Yes'), ('INPROGRESS', 'In Progress'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('leash_trained', models.CharField(blank=True, choices=[('YES', 'Yes'), ('INPROGRESS', 'In Progress'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('crate_trained', models.CharField(blank=True, choices=[('YES', 'Yes'), ('INPROGRESS', 'In Progress'), ('UNKNOWN', 'Unknown')], max_length=10, null=True)),
                ('adopted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopt_person', to=settings.AUTH_USER_MODEL)),
                ('fostered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='foster_person', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registered_date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.TextField(max_length=255)),
                ('date_time_created', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adopt.pet')),
            ],
            options={
                'ordering': ['-date_time_created'],
            },
        ),
    ]
