# Generated by Django 5.0.1 on 2024-04-19 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_foster_family',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_shelter',
        ),
    ]
