# Generated by Django 5.0.1 on 2024-04-21 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0003_alter_pet_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_time']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='entry',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_time_created',
            new_name='created_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='pet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='adopt.pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'Small (1-10kg)'), ('M', 'Medium (11-26kg)'), ('L', 'Large (27-45kg)'), ('EX', 'Extra Large (46+kg)')], max_length=50, null=True),
        ),
    ]
