# Generated by Django 5.0.1 on 2024-04-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0004_alter_comment_options_rename_user_comment_commenter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='province',
        ),
        migrations.AddField(
            model_name='organization',
            name='area',
            field=models.CharField(choices=[('BANGKOK', 'Bangkok'), ('NONTHABURI', 'Nonthaburi'), ('PHUKET', 'PHUKET'), ('PATTAYA', 'Pattaya')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('BANGKOK', 'Bangkok'), ('NONTHABURI', 'Nonthaburi'), ('PHUKET', 'PHUKET'), ('PATTAYA', 'Pattaya')], max_length=100, null=True),
        ),
    ]
