# Generated by Django 5.0.1 on 2024-04-23 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0005_remove_user_province_organization_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='area',
            field=models.CharField(choices=[('BANGKOK', 'Bangkok'), ('NONTHABURI', 'Nonthaburi'), ('PHUKET', 'Phuket'), ('PATTAYA', 'Pattaya')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.CharField(choices=[('BANGKOK', 'Bangkok'), ('NONTHABURI', 'Nonthaburi'), ('PHUKET', 'Phuket'), ('PATTAYA', 'Pattaya')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='adopt.organization'),
        ),
    ]
