# Generated by Django 5.0.1 on 2024-05-03 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopt', '0007_alter_pet_adopted_by_alter_pet_fostered_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-registered_date']},
        ),
    ]
